import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";
// import ProfileImageGuard from "./(website)/profile/_components/profile-image-guard";
import { Suspense } from "react";
import LangConfig from "./lang-config";
import Script from "next/script";
import TranslateProvider from "@/components/providers/TranslateProvider";

const daggerSquare = localFont({
  src: "./fonts/DAGGERSQUARE.otf",
  variable: "--font-dagger-square",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Analytic Soccer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={daggerSquare.variable}>
      <head>
        <Script id="gtm-script" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-NCJ7R7KQ');`}
        </Script>
      </head>
      <body className={`font-dagger antialiased`}>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-NCJ7R7KQ"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>

        <AuthProvider>
          <AppProvider>
            {/* <ProfileImageGuard> */}
            {/* ✅ Google translate container */}
            {/* <div id="google_translate_element"></div> */}
            <div
              id="google_translate_element"
              style={{ display: "none" }}
            ></div>

            {/* ✅ Loaded only on client */}
            <Suspense fallback={null}>
              <LangConfig />
            </Suspense>
            <Suspense fallback={null}>
              <TranslateProvider />
            </Suspense>
            {children}

            <Script
              src="//translate.google.com/translate_a/element.js?cb=TranslateInit"
              strategy="afterInteractive"
            />
            {/* </ProfileImageGuard> */}

            <Toaster />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";
// import AuthProvider from "@/components/providers/AuthProvider";
// import AppProvider from "@/components/providers/AppProvider";
// // import ProfileImageGuard from "./(website)/profile/_components/profile-image-guard";
// import { Suspense } from "react";
// import LangConfig from "./lang-config";
// import Script from "next/script";
// import TranslateProvider from "@/components/providers/TranslateProvider";

// const daggerSquare = localFont({
//   src: "./fonts/DAGGERSQUARE.otf",
//   variable: "--font-dagger-square",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Analytic Soccer",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={daggerSquare.variable}>
//       <body className={`font-dagger antialiased`}>
//         <AuthProvider>
//           <AppProvider>
//             {/* <ProfileImageGuard> */}
//               {/* ✅ Google translate container */}
//               {/* <div id="google_translate_element"></div> */}
//               <div id="google_translate_element" style={{ display: "none" }}></div>

//               {/* ✅ Loaded only on client */}
//               <Suspense fallback={null}>
//                 <LangConfig />
//               </Suspense>
//               <Suspense fallback={null}>
//                 <TranslateProvider />
//               </Suspense>
//               {children}

//               <Script
//                 src="//translate.google.com/translate_a/element.js?cb=TranslateInit"
//                 strategy="afterInteractive"
//               />
//             {/* </ProfileImageGuard> */}

//             <Toaster />
//           </AppProvider>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
