import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";
import ProfileImageGuard from "./(website)/profile/_components/profile-image-guard";

const daggerSquare = localFont({
  src: "./fonts/DAGGERSQUARE.otf",
  variable: "--font-dagger-square",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Analytic Soccer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={daggerSquare.variable}>
      <body className={`font-dagger antialiased`}>
        <AuthProvider>
          <AppProvider>
            <ProfileImageGuard>{children}</ProfileImageGuard>

            <Toaster />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
